version: "3"
services:
  neo4j:
    image: neo4j:3.4.12
    container_name: neo4j-dev
    environment:
      - "NEO4J_dbms_security_auth__enabled=false"
      - "NEO4J_elasticsearch_host__name=http://elastic:9200"
      - "NEO4J_elasticsearch_index__spec=clubs:Club(name, uid),users:User(name,email,uid)"
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    environment:
      - discovery.type=single-node
    container_name: elasticsearch-dev
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://elastic:9200
    ports:
      - "5601:5601"
