openapi: "3.0.1"
info:
  version: 1.0.0
  title: Event API
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /clubs/{uuid}:
    get:
      summary: get Club
      operationId: readClub
      tags:
        - Clubs
      parameters:
        - name: uuid
          in: path
          description: uniqe id of Club
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A paged array of Clubs
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Club"
  /clubs:
    post:
      security:
        - bearerAuth: []
      summary: create Club
      operationId: createClub
      tags:
        - Clubs
      requestBody:
        content:
          application/json:
            schema:
             $ref: "#/components/schemas/Club"
      responses:
        '200':
          description: Created
components:
  securitySchemes:
      bearerAuth:            # arbitrary name for the security scheme
        type: http
        scheme: bearer
        bearerFormat: JWT    # optional, arbitrary value for documentation purposes

  schemas:
    Club:
      properties:
        name:
          type: string
    User:
      properties:
        admin:
          type: boolean
        provider:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        nickName:
          type: string
        description:
          type: string
        userID:
          type: string
        avatarURL:
          type: string
        location:
          type: string          
          